### ISSUE TITLE
handle error

### ISSUE THREAD

**Issue by eroux** [buda-base/volume-manifest-builder#2]
The following error occurred on W21808-0117: 

```
The object does not exist.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2315, in open
    fp.seek(0)
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manifestforwork.py", line 222, in <module>
    main()
  File "./manifestforwork.py", line 25, in main
    manifestForList(sys.argv[1])
  File "./manifestforwork.py", line 39, in manifestForList
    manifestForWork(client, bucket, workRID)
  File "./manifestforwork.py", line 48, in manifestForWork
    manifestForVolume(client, bucket, workRID, vi)
  File "./manifestforwork.py", line 58, in manifestForVolume
    manifest = generateManifest(bucket, s3folderPrefix, vi.imageList)
  File "./manifestforwork.py", line 180, in generateManifest
    width, heigth = dimensionsFromBlobImage(blob)
  File "./manifestforwork.py", line 194, in dimensionsFromBlobImage
    im = Image.open(blob)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2317, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'NoneType' object has no attribute 'read'
```

This is probably an image listed in the image list but not present on S3. This kind of case should be handled properly, and logged in stderr.

**Comment by eroux** [comment]
fixed
